version: '3'
services:
  db:
    build: 
      context: ./
      dockerfile: ./build/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  app:
    build:
      context: ./
      dockerfile: ./build/app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      GO_TEMPLATE_MYSQL_HOST: db
      GO_TEMPLATE_MYSQL_DATABASE: ${MYSQL_DATABASE}
      GO_TEMPLATE_MYSQL_USER: ${MYSQL_USER}
      GO_TEMPLATE_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      GO_TEMPLATE_ENV: ${APP_ENV}
    restart: always

volumes:
  db-data: