CREATE DATABASE IF NOT EXISTS cafe;
USE cafe;

CREATE TABLE IF NOT EXISTS cafe (
    Uid BIGINT NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Address VARCHAR(100) NOT NULL,
    CreateTime TIME NOT NULL,
    MotifyTime TIME,
    PRIMARY KEY (Uid)
);